/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PruneRouteImport } from './routes/prune'
import { Route as OldRouteImport } from './routes/old'
import { Route as MeRouteImport } from './routes/me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIdRouteImport } from './routes/lists/$id'

const PruneRoute = PruneRouteImport.update({
  id: '/prune',
  path: '/prune',
  getParentRoute: () => rootRouteImport,
} as any)
const OldRoute = OldRouteImport.update({
  id: '/old',
  path: '/old',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIdRoute = ListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/old': typeof OldRoute
  '/prune': typeof PruneRoute
  '/lists/$id': typeof ListsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/old': typeof OldRoute
  '/prune': typeof PruneRoute
  '/lists/$id': typeof ListsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/old': typeof OldRoute
  '/prune': typeof PruneRoute
  '/lists/$id': typeof ListsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/me' | '/old' | '/prune' | '/lists/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/me' | '/old' | '/prune' | '/lists/$id'
  id: '__root__' | '/' | '/me' | '/old' | '/prune' | '/lists/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeRoute: typeof MeRoute
  OldRoute: typeof OldRoute
  PruneRoute: typeof PruneRoute
  ListsIdRoute: typeof ListsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prune': {
      id: '/prune'
      path: '/prune'
      fullPath: '/prune'
      preLoaderRoute: typeof PruneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old': {
      id: '/old'
      path: '/old'
      fullPath: '/old'
      preLoaderRoute: typeof OldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$id': {
      id: '/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeRoute: MeRoute,
  OldRoute: OldRoute,
  PruneRoute: PruneRoute,
  ListsIdRoute: ListsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
