name: Frontend Build

on:
  push:
    paths:
      - "fe/**"
  pull_request:
    paths:
      - "fe/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fe
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - run: bun run build
